### PR TITLE
Be more defensive in etcd polling, catch various HTTP-related exceptions...

### LINKED ISSUE #415: Raw timemout exception leaking through urllib3/python-etcd
Nick Bartos at Piston Cloud is hitting these exceptions when he gets an expected timeout.  I think the exception is supposed to be caught inside one of the libs we're using and wrapped in an expected exception.

```
Apr 18 20:39:45.943393 10.41.0.18 err calico-felix: Exception processing 28b1b069d818 (watch_etcd)
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/calico/felix/actor.py", line 237, in _step
  File "/usr/lib64/python2.7/site-packages/calico/felix/fetcd.py", line 201, in watch_etcd
  File "/usr/lib64/python2.7/site-packages/etcd/client.py", line 348, in read
  File "/usr/lib64/python2.7/site-packages/etcd/client.py", line 604, in api_execute
  File "/usr/lib64/python2.7/site-packages/urllib3/response.py", line 130, in data
  File "/usr/lib64/python2.7/site-packages/urllib3/response.py", line 170, in read
  File "/usr/lib64/python2.7/httplib.py", line 549, in read
  File "/usr/lib64/python2.7/httplib.py", line 591, in _read_chunked
  File "/usr/lib64/python2.7/socket.py", line 476, in readline
  File "/usr/lib64/python2.7/site-packages/gevent/socket.py", line 392, in recv
  File "/usr/lib64/python2.7/site-packages/gevent/socket.py", line 298, in _wait
  File "/usr/lib64/python2.7/site-packages/gevent/hub.py", line 341, in wait
  File "/usr/lib64/python2.7/site-packages/gevent/hub.py", line 568, in get
  File "/usr/lib64/python2.7/site-packages/gevent/hub.py", line 331, in switch
timeout: timed out

Apr 18 20:16:48.483014 10.41.0.18 err calico-felix: Exception processing f1433ca1d393 (load_config)
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/calico/felix/actor.py", line 237, in _step
  File "/usr/lib64/python2.7/site-packages/calico/felix/fetcd.py", line 69, in load_config
  File "/usr/lib64/python2.7/site-packages/calico/felix/actor.py", line 508, in queue_fn
  File "/usr/lib64/python2.7/site-packages/calico/felix/fetcd.py", line 91, in wait_for_ready
  File "/usr/lib64/python2.7/site-packages/etcd/client.py", line 348, in read
  File "/usr/lib64/python2.7/site-packages/etcd/client.py", line 569, in api_execute
  File "/usr/lib64/python2.7/site-packages/urllib3/request.py", line 75, in request
  File "/usr/lib64/python2.7/site-packages/urllib3/request.py", line 88, in request_encode_url
  File "/usr/lib64/python2.7/site-packages/urllib3/poolmanager.py", line 155, in urlopen
  File "/usr/lib64/python2.7/site-packages/urllib3/connectionpool.py", line 541, in urlopen
  File "/usr/lib64/python2.7/site-packages/urllib3/connectionpool.py", line 370, in _make_request
ConnectTimeoutError: (<urllib3.connectionpool.HTTPConnectionPool object at 0x7f30dbd686d0>, 'Connection to 10.41.5.5 timed out. (connect timeout=10)')
```

### PR DESCRIPTION
**Pull request by fasaxc**
python-etcd isn't great at wrapping all exceptions that urllib3 and the libraries underneath it can raise.  Be defensive and catch all exceptions from urllib3 as well as socker.timeout, which seems to get leaked when we're running on top of gevent.

Also fix the import order in felix.py.  We were importing some items before we monkey-patched using gevent.  That's asking for trouble.  (I thought I'd already fixed that :-()

Should fix #415.

### CODE REVIEW

**Comment by fasaxc** [comment]
@Lukasa do you have time to look at his today?

**Comment by fasaxc** [comment]
Ooh, just spotted another issue that might be the root-cause of that timeout leak...

**Comment by fasaxc** [comment]
Ugh, I thought I'd fixed the import-before-monkeypatch issue ages ago.  That's probably what was causing the timeout error to leak out of urllib3.

**Comment by Lukasa** [comment]
Given that you think there's still an outstanding bug, I may hold off on merging this until you chase it down @fasaxc.

**Comment by fasaxc** [comment]
Sorry, I wasn't clear in my message that I had already pushed a fix (d4cc8ae).  This has now had an FV run against it but the FVs don't yet hit all the exception cases.  I'll try to validate the different cases by hand...

**Comment by fasaxc** [comment]
I've tested this manually and I can hit the ConnectionTimeout/ReadTimeout errors by using iptables to drop packets to etcd/stopping etcd;  I also checked that I can get an EtcdEventIndexCleared.  I can't seem to hit the leaked timeout error anymore, I suspect that is fixed by moving the monkey-patching to the top of the imports.  Is it crazy to leave that in as belt-and-braces?

**Comment by fasaxc** [comment]
@robbrockbank please can you pick this one up since Cory is probably OOF by now.

**Comment by robbrockbank** [comment]
It seems reasonable to me to leave the exception branch in place, but shouldn't it therefore warrant something higher than debug logging?

**Comment by fasaxc** [comment]
Sounds good, I've bumped it up to warning since I think we handle it correctly if it does occur.

**Comment by robbrockbank** [comment]
Chatted to Shaun about the exceptions here.  Looks good to me and is passing FV and hand testing.

**Pull request merged**
