### PR TITLE
Rhel7 fixes

### PR DESCRIPTION
**Pull request by matthewdupre**
These are the changes needed to make Calico work with RedHat 7 and Juno.

### CODE REVIEW

**Comment by neiljerram** [comment]
All looking good, modulo my specific comments...

**Comment by matthewdupre** [comment]
Markups made and 578d4eb removed.

**Comment by neiljerram** [comment]
All looks great, now, thanks.  So I wonder, are we safe to merge?

**Comment by Lukasa** [comment]
Not safe to merge until tomorrow.

**Comment by neiljerram** [comment]
@Lukasa I'm working on a plan to allow us to merge today.  We have quite a bit of stuff backed up now, and probably situations like the current demo will start cropping up more frequently... so we need a plan.  Watch this space!

**Pull request merged**
