### PR TITLE
Add list of third-party attributions

### PR DESCRIPTION
**Pull request by alexwlchan**
This is a straight copy of the file README.txt from the calico-docs repo, copied here so it doesn't get lost.when the calico-docs repo is retired.

Related: https://github.com/Metaswitch/calico-docs/issues/3

### CODE REVIEW

**Comment by Lukasa** [comment]
@neiljerram and I were quite unsure that we should reproduce that notice in this repository, given that this repository does not distribute or contain any code from any of those projects in it. My alternative is in #292.

That said, someone who isn't me or neil should decide which of these approaches to take. @ed-harrison seems like a good start!

**Comment by Lukasa** [comment]
ok to test

**Comment by ed-harrison** [comment]
I'm happy to agree with Cory's plan (sorry Alex!).  I'll merge Cory's suggestion and then just run it by the legal department to confirm they are happy.

**Comment by alexwlchan** [comment]
Seems sensible. I'll clean up after myself.

**Pull request closed without merging**
