### PR TITLE
Fix Felix keepalives

### PR DESCRIPTION
**Pull request by plwhite**
Fixes bug #110

### CODE REVIEW

**Comment by plwhite** [comment]
Hold off. I just hit an issue in manual testing...

**Comment by plwhite** [comment]
We have something of a problem in that the OpenStack plugin cannot handle the HEARTBEAT messages - fix this for docker, break OpenStack. That's bad news.

**Comment by Lukasa** [comment]
Neil, you have the action to update this pull request with code that fixes the plugin side of this bug, as necessary.

**Comment by plwhite** [comment]
Here is an extract from `server.log`

    2015-01-15 16:20:48.641 2228 INFO calico.openstack.mech_calico [-] Felix-ROUTER RX [^@k<8B>E<FC>] {u'type': u'HEARTBEAT'}
    2015-01-15 16:20:48.641 2228 INFO calico.openstack.mech_calico [-] HEARTBEAT
    2015-01-15 16:20:48.641 2228 ERROR calico.openstack.mech_calico [-] Exception in Felix-facing ROUTER socket thread
    2015-01-15 16:20:48.641 2228 TRACE calico.openstack.mech_calico Traceback (most recent call last):
    2015-01-15 16:20:48.641 2228 TRACE calico.openstack.mech_calico   File "/usr/lib/python2.7/dist-packages/calico/openstack/mech_calico.py", line 304, in felix_router_thread
    2015-01-15 16:20:48.641 2228 TRACE calico.openstack.mech_calico     json.dumps(rq).encode('utf-8'))
    2015-01-15 16:20:48.641 2228 TRACE calico.openstack.mech_calico   File "/usr/lib/python2.7/dist-packages/eventlet/green/zmq.py", line 294, in send_multipart
    2015-01-15 16:20:48.641 2228 TRACE calico.openstack.mech_calico     if flags & NOBLOCK:
    2015-01-15 16:20:48.641 2228 TRACE calico.openstack.mech_calico TypeError: unsupported operand type(s) for &: 'str' and 'int'
    2015-01-15 16:20:48.641 2228 TRACE calico.openstack.mech_calico
    2015-01-15 16:20:48.642 2228 INFO calico.openstack.mech_calico [-] Felix-ROUTER: wait to receive next message

**Comment by Lukasa** [comment]
Hurrah! :cake:

**Pull request merged**
