### PR TITLE
Initial stab at config stuff.

### PR DESCRIPTION
**Pull request by plwhite**
Conflicts:
	calico/felix/felix.py
	calico/felix/frules.py

### CODE REVIEW

**Comment by plwhite** [comment]
Please test me

**Comment by plwhite** [comment]
Please test me

**Comment by plwhite** [comment]
Retest this please

**Comment by plwhite** [comment]
OK to test

**Comment by Lukasa** [comment]
retest this please

**Comment by Lukasa** [comment]
retest this please

**Pull request merged**
