### PR TITLE
Do not log from weakref callbacks.

### PR DESCRIPTION
**Pull request by Lukasa**
See #587 for details.

### CODE REVIEW

**Comment by plwhite** [comment]
Code is all fine, assuming that print to stderr is not monkey patched away.

One minor thing - shouldn't it go into the `changelog` as a fix that we have made?

**Comment by Lukasa** [comment]
Yes it should, I'll push up a changelog entry.

**Comment by Lukasa** [comment]
@plwhite done.

**Comment by Lukasa** [comment]
Sorry, introduced a merge conflict that I've now resolved.

**Pull request merged**
