### PR TITLE
Increase number of file descriptors in calico-felix.conf

### PR DESCRIPTION
**Pull request by alexwlchan**
This increases the number of file descriptors available to Felix, which should mitigate issue #534 (Felix gets sad when it can't create any more VMs/tap interfaces).

I picked 32K just because it was the first number suggested in that issue. We don't have any documentation for editing calico-felix.conf, so I assume it gets put in place by our installers. This is the only felix.conf file in the /calico repo, so I'm guessing this is it.

### CODE REVIEW

**Comment by Lukasa** [comment]
Do we not need to make a similar change on Ubuntu?

**Comment by plwhite** [comment]
I think this isn't quite right. That file is only used for RPMs, not for the normal upstart job (I think). That means you should also change debian/calico-felix.upstart

Net of this is that 

* You should change that file too.
* Run the changes past @matthewdupre since he's more expert in this area.
* Add a changelog entry for this change.

**Comment by plwhite** [comment]
Comments crossed - @Lukasa and I spotted the same thing, but he didn't get distracted by a mail in the middle!

**Comment by alexwlchan** [comment]
Added the Debian file and changelog entry.

**Comment by matthewdupre** [comment]
Debian and RHEL 6.5 upstart job changes are fine, but you also need to update the RHEL 7 systemd service file (rpm/calico-felix.service).

Specifically LimitNOFILE=32000 in the [service] section - see http://man7.org/linux/man-pages/man5/systemd.exec.5.html.

**Pull request merged**
