### PR TITLE
Improve logging around IDs, refcounting and iptables programming.

### PR DESCRIPTION
**Pull request by fasaxc**
Just a bunch of logging improvements and a few asserts added while tracking down today's bugs.

### CODE REVIEW

**Comment by Lukasa** [comment]
Lots of these logging improvements consist simply of elevating debug logs to info level. What's the reasoning behind that?

**Comment by fasaxc** [comment]
@Lukasa I think it was a mistake to have the "active" actors (i.e. the ones that handle the things this host actually cares about) log their state changes at debug.  There should be only a few of them (<500?) so, while these changes might have an impact, they shouldn't be _too_ chatty.  Without logs for their updates and life-cycle changes, the diags we were getting from the FV weren't enough to go on.  

The only one I'm a little scared about is tracing out the raw iptables updates and deps.  Those are very valuable but they could be large.

**Comment by Lukasa** [comment]
It's still not clear to me why we're deciding to impact *all* users by logging this stuff at debug level, rather than just solving the problem for the FV case by turning the logging level up for the FV.

I'm worried about us generating a truly unholy amount of logs.

**Comment by apollitt** [comment]
We need to get our logs to a level where we can diagnose problems in the field.  If based on our FV debugging experience we think we need to have better logging for that, then I suspect the same applies to our field logging.  Note I said "better logging".  In some cases this may mean "more logs", but not necessarily.

**Comment by fasaxc** [comment]
I think this tunes it to a better balance for diagnosing general problems.  We don't log every update, only changes that impact this node.

**Pull request merged**
