### PR TITLE
Actually save off the endpoints in the endpoint index.

### LINKED ISSUE #521: ipsets only getting added to in churn test
I dug into the issue @DaveLangridge mentioned in #520 and it looks like the dataplane has got out of sync with etcd.  With me to investigate.

### PR DESCRIPTION
**Pull request by fasaxc**
Fixes #521.

### CODE REVIEW

**Comment by robbrockbank** [comment]
LGTM - are there any UT changes for this?

**Comment by fasaxc** [comment]
Actually, that file has been reviewed so I'm unblocked on adding UTs.  I'll see if I can at least cover what I've changed...

**Comment by robbrockbank** [comment]
discussed with @fasaxc - UTs to be in subsequent pull req so happy for this to go in.

**Comment by fasaxc** [comment]
UTs added under commit 4ef12138e9e1188fd5464d9fde5a2e902f33817b, which will find its way into master via the HA feature branch.

**Pull request merged**
