### PR TITLE
Fix bad assert left in after fix to issue 460

### PR DESCRIPTION
**Pull request by plwhite**
Also, add changelog entry for issue 460 (missed in initial fix).

### CODE REVIEW

**Comment by Lukasa** [comment]
@plwhite Changes should go in CHANGES.md, not in debian/changelog.

**Comment by matthewdupre** [comment]
Cory's right in that you should remove the debian changelog entry.  I can add to that that the package build failure is because it wasn't formatted properly either (it's very picky about the signature line).

**Comment by matthewdupre** [comment]
If we can cheaply reintroduce the assert that would be nice, otherwise just need the changelog -> CHANGES.md fix before I can merge.

**Comment by matthewdupre** [comment]
@plwhite Strictly the changelog entry should go under #0.22-dev (or whatever the next release is), but we'll just fix that when we make the release.

**Pull request merged**
