### PR TITLE
DO NOT MERGE Work in progress on cleanup/support for anycast IPs.

### PR DESCRIPTION
**Pull request by fasaxc**
Pull req to trigger a build.

### CODE REVIEW

**Comment by Symmetric** [comment]
```
2015-04-14 21:05:19,566 [DEBUG][11] calico.felix.actor 228: Message af9a4f6bdba3 (on_endpoint_update) recd by IpsetManager(IPv6) from EtcdWatcher (processing 4791a6399757), queue length 0
2015-04-14 21:05:19,567 [ERROR][11] calico.felix.actor 235: Exception processing af9a4f6bdba3 (on_endpoint_update)
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/calico/felix/actor.py", line 233, in _step
    result = msg.method()
  File "/usr/lib/python2.7/dist-packages/calico/felix/ipsets.py", line 201, in on_endpoint_update
    new_prof_id = endpoint.get["profile_id"]
TypeError: 'builtin_function_or_method' object has no attribute '__getitem__'
```

**Comment by Symmetric** [comment]
Also,
```
2015-04-13 22:06:55,401 [ERROR][4] calico.felix.fiptables 604: Failed to run iptables-restore.
Output:

Error:
iptables-restore: line 2 failed

Input was:
*nat
--delete PREROUTING --jump felix-PREROUTING
--insert PREROUTING --jump felix-PREROUTING
COMMIT

2015-04-13 22:06:55,402 [ERROR][4] calico.felix.fiptables 606: Non-retryable error on line 2: '--delete PREROUTING --jump felix-PREROUTING'
```
May be benign...

**Comment by Symmetric** [comment]
New error:
```
2015-04-14 21:54:54,383 [DEBUG][10] calico.felix.actor 228: Message 8e32e4fc120c (on_endpoint_update) recd by IpsetManager(IPv4) from EtcdWatcher (processing c5d2223fedd5), queue length 0
2015-04-14 21:54:54,384 [ERROR][10] calico.felix.actor 235: Exception processing 8e32e4fc120c (on_endpoint_update)
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/calico/felix/actor.py", line 233, in _step
    result = msg.method()
  File "/usr/lib/python2.7/dist-packages/calico/felix/ipsets.py", line 249, in on_endpoint_update
    self.objects_by_id[tag].add_member(ip)
  File "/usr/lib/python2.7/dist-packages/calico/felix/actor.py", line 507, in queue_fn
    assert async_set, "All cross-actor event calls must specify async arg."
AssertionError: All cross-actor event calls must specify async arg.
```

**Comment by Symmetric** [comment]
Another issue:
```
2015-04-14 22:21:09,421 [ERROR][10] calico.felix.actor 235: Exception processing 8be4ac04fe9e (on_endpoint_update)
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/calico/felix/actor.py", line 233, in _step
    result = msg.method()
  File "/usr/lib/python2.7/dist-packages/calico/felix/ipsets.py", line 253, in on_endpoint_update
    self._add_mapping(tag, endpoint_id, ip)
  File "/usr/lib/python2.7/dist-packages/calico/felix/ipsets.py", line 289, in _add_mapping
    self.objects_by_id.add_member(ip_address, async=True)
AttributeError: 'dict' object has no attribute 'add_member'
```
This seems to have prevented one existing workload from being added to my test profile, but the rest of the testing went ok.

**Comment by fasaxc** [comment]
Pushed a fix.

**Comment by Symmetric** [comment]
Hmm, now seeing this:

```
2015-04-15 00:13:42,547 [DEBUG][10] calico.felix.ipsets 222: Profile ID changed from %s to %s
2015-04-15 00:13:42,547 [DEBUG][10] calico.felix.ipsets 289: Adding 192.168.1.14 to active tag PROF_Z
2015-04-15 00:13:42,547 [ERROR][10] calico.felix.actor 235: Exception processing 048029bfc14f (on_endpoint_update)
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/calico/felix/actor.py", line 233, in _step
    result = msg.method()
  File "/usr/lib/python2.7/dist-packages/calico/felix/ipsets.py", line 253, in on_endpoint_update
    self._add_mapping(tag, endpoint_id, ip)
  File "/usr/lib/python2.7/dist-packages/calico/felix/ipsets.py", line 290, in _add_mapping
    self.objects_by_id[endpoint_id].add_member(ip_address, async=True)
KeyError: u'0d0a661ee30411e4b5730800272d7481'
```

**Pull request closed without merging**
