### PR TITLE
Add PyPy support to Tox.

### PR DESCRIPTION
**Pull request by Lukasa**
Where we can, we should remain functional on PyPy. At least, that's what I think. Admittedly, that's not an agreed position in the team, but I'd like to propose it.

My mechanism for proposing it is to add PyPy as a test environment in tox. This PR does exactly that. Two small notes:

- we don't support coverage under PyPy because it's dog-slow. The two just don't play well together.
- we don't support the OpenStack plugin under PyPy. Neutron won't run under PyPy anyway (AFAIK), so it doesn't matter, and the tests fail for mysterious reasons. In the future it'd be good to lift this limitation, but for now we're ok.

People who care about this sort of thing (PyPy etc.), please voice your opinions here!

### CODE REVIEW

**Comment by Lukasa** [comment]
This PR also contains a fix to some overbroad mocking of 'time'. Weirdly, I only ever saw this in the PyPy runs, but it appeared to be wrong in general, so I fixed it up here.

**Comment by Lukasa** [comment]
Tagging some people who might care explicitly: @fasaxc @neiljerram @plwhite @matthewdupre.

**Comment by Lukasa** [comment]
Turns out nose-exclude does not play well at all with PyPy. That's sad =(

**Comment by Lukasa** [comment]
Hurrah, clean run with PyPy!

**Comment by fasaxc** [comment]
I like the idea of running on PyPy; now if only their logging module wasn't a total train-wreck for perf (or it was last time I looked) due to needing to look at stack frames.

**Comment by Lukasa** [comment]
Running on PyPy has a separate problem now, which is that gevent on PyPy is a pain in the ass (gevent's most recent release doesn't support PyPy). That said, I think if we're interested we should actually check performance, because arguably the jitter could inline a lot of frame information if it needed to.

**Comment by Lukasa** [comment]
This branch fell so far behind I needed to do a catch-up merge, because the rebase just got hopelessly lost. (938 commits behind, by my count)

**Comment by Lukasa** [comment]
Alright, now we know that some tests fail on PyPy. @fasaxc, this may be of interest to you, though admittedly probably not in the short term. Here's the test output:

```
======================================================================
ERROR: test_cleanup_with_dependencies (calico.felix.test.test_fiptables.TestIptablesUpdater)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/lib/jenkins/workspace/pull-request/calico/felix/test/test_fiptables.py", line 89, in tearDown
    super(TestIptablesUpdater, self).tearDown()
  File "/var/lib/jenkins/workspace/pull-request/calico/felix/test/base.py", line 25, in tearDown
    self.assertFalse(self._m_exit.called)
AssertionError: True is not false
-------------------- >> begin captured logging << --------------------
calico.felix.actor: INFO: IptablesUpdater(v4) created.
calico.felix.actor: DEBUG: Message 29f49ea843d2 (_refresh_chains_in_dataplane) sent by ActorForTesting (processing None) to IptablesUpdater(v4), queue length 0
calico.felix.test.test_fiptables: DEBUG: iptables-restore input:

        *filter
        :INPUT DROP [10:505]
        :FORWARD DROP [0:0]
        :OUTPUT ACCEPT [40:1600]
        # These non-felix chains should be ignored
        :ignore-me -
        :ignore-me-too -
        # These are left-over felix chains.  Some depend on each other.  They
        # can only be cleaned up in the correct order.
        :felix-foo - [0:0]
        :felix-bar -
        :felix-foo -
        :felix-baz -
        :felix-biff -
        --append felix-foo --src 10.0.0.1/32 --jump felix-bar
        # baz depends on biff; cleanup needs to detect that.
        --append felix-baz --src 10.0.0.2/32 --jump felix-biff
        --append felix-biff --src 10.0.0.3/32 --jump DROP
        --append ignore-me --jump ignore-me-too
        --append ignore-me-too --jump DROP
        
calico.felix.test.test_fiptables: DEBUG: Processing table filter
calico.felix.test.test_fiptables: DEBUG: Forward declaration ['INPUT', 'DROP', '[10:505]'], flushing chain
calico.felix.test.test_fiptables: DEBUG: Forward declaration ['FORWARD', 'DROP', '[0:0]'], flushing chain
calico.felix.test.test_fiptables: DEBUG: Forward declaration ['OUTPUT', 'ACCEPT', '[40:1600]'], flushing chain
calico.felix.test.test_fiptables: DEBUG: Forward declaration ['ignore-me', '-'], flushing chain
calico.felix.test.test_fiptables: DEBUG: Forward declaration ['ignore-me-too', '-'], flushing chain
calico.felix.test.test_fiptables: DEBUG: Forward declaration ['felix-foo', '-', '[0:0]'], flushing chain
calico.felix.test.test_fiptables: DEBUG: Forward declaration ['felix-bar', '-'], flushing chain
calico.felix.test.test_fiptables: DEBUG: Forward declaration ['felix-foo', '-'], flushing chain
calico.felix.test.test_fiptables: DEBUG: Forward declaration ['felix-baz', '-'], flushing chain
calico.felix.test.test_fiptables: DEBUG: Forward declaration ['felix-biff', '-'], flushing chain
calico.felix.test.test_fiptables: DEBUG: Rule op: --append, chain name: felix-foo
calico.felix.test.test_fiptables: DEBUG: Action felix-bar
calico.felix.test.test_fiptables: DEBUG: Rule op: --append, chain name: felix-baz
calico.felix.test.test_fiptables: DEBUG: Action felix-biff
calico.felix.test.test_fiptables: DEBUG: Rule op: --append, chain name: felix-biff
calico.felix.test.test_fiptables: DEBUG: Action DROP
calico.felix.test.test_fiptables: DEBUG: Rule op: --append, chain name: ignore-me
calico.felix.test.test_fiptables: DEBUG: Action ignore-me-too
calico.felix.test.test_fiptables: DEBUG: Rule op: --append, chain name: ignore-me-too
calico.felix.test.test_fiptables: DEBUG: Action DROP
calico.felix.actor: DEBUG: Message aa25913e2cd3 (rewrite_chains) sent by ActorForTesting (processing None) to IptablesUpdater(v4), queue length 1
calico.felix.actor: DEBUG: Message 29f49ea843d2 (_refresh_chains_in_dataplane) recd by IptablesUpdater(v4) from ActorForTesting (processing None), queue length 1
calico.felix.actor: DEBUG: Finishing message batch
calico.felix.fiptables: DEBUG: Chains we'd like to delete: set([])
calico.felix.fiptables: DEBUG: Chains we still need for some reason: set([])
calico.felix.fiptables: DEBUG: Chains we can delete: set([])
calico.felix.fiptables: DEBUG: Affected chains: deletes=set([]), updates=set([]), stubs=set([])
calico.felix.fiptables: INFO: IptablesUpdater<queue_len=1,live=True,msg=None> no updates in this batch.
calico.felix.fiptables: DEBUG: Batch time: 0.09 1
calico.felix.actor: DEBUG: Message aa25913e2cd3 (rewrite_chains) recd by IptablesUpdater(v4) from ActorForTesting (processing None), queue length 0
calico.felix.fiptables: INFO: Iptables update: {'felix-foo': ['--append felix-foo --jump felix-bar', '--append felix-foo --jump felix-baz', '--append felix-foo --jump felix-boff'], 'felix-bar': ['--append felix-bar --jump ACCEPT']}
calico.felix.fiptables: INFO: Iptables deps: {'felix-foo': set(['felix-baz', 'felix-boff', 'felix-bar']), 'felix-bar': set([])}
calico.felix.fiptables: DEBUG: Storing updates to chain felix-foo
calico.felix.fiptables: DEBUG: Storing updates to chain felix-bar
calico.felix.actor: DEBUG: Finishing message batch
calico.felix.fiptables: DEBUG: Chains we'd like to delete: set([])
calico.felix.fiptables: DEBUG: Chains we still need for some reason: set(['felix-boff', 'felix-baz', 'felix-foo', 'felix-bar'])
calico.felix.fiptables: DEBUG: Chains we can delete: set([])
calico.felix.fiptables: DEBUG: Affected chains: deletes=set([]), updates=set(['felix-foo', 'felix-bar']), stubs=set(['felix-boff', 'felix-baz'])
calico.felix.test.test_fiptables: DEBUG: iptables-restore input:
*filter
:felix-boff -
:felix-foo -
:felix-bar -
--flush felix-boff
--append felix-boff --jump DROP -m comment --comment "WARNING Missing chain DROP:"
--flush felix-foo
--append felix-foo --jump felix-bar
--append felix-foo --jump felix-baz
--append felix-foo --jump felix-boff
--flush felix-bar
--append felix-bar --jump ACCEPT
COMMIT
calico.felix.test.test_fiptables: DEBUG: Processing table filter
calico.felix.test.test_fiptables: DEBUG: Forward declaration ['felix-boff', '-'], flushing chain
calico.felix.test.test_fiptables: DEBUG: Forward declaration ['felix-foo', '-'], flushing chain
calico.felix.test.test_fiptables: DEBUG: Forward declaration ['felix-bar', '-'], flushing chain
calico.felix.test.test_fiptables: DEBUG: Rule op: --flush, chain name: felix-boff
calico.felix.test.test_fiptables: DEBUG: Rule op: --append, chain name: felix-boff
calico.felix.test.test_fiptables: DEBUG: Action DROP
calico.felix.test.test_fiptables: DEBUG: Rule op: --flush, chain name: felix-foo
calico.felix.test.test_fiptables: DEBUG: Rule op: --append, chain name: felix-foo
calico.felix.test.test_fiptables: DEBUG: Action felix-bar
calico.felix.test.test_fiptables: DEBUG: Rule op: --append, chain name: felix-foo
calico.felix.test.test_fiptables: DEBUG: Action felix-baz
calico.felix.test.test_fiptables: DEBUG: Rule op: --append, chain name: felix-foo
calico.felix.test.test_fiptables: DEBUG: Action felix-boff
calico.felix.test.test_fiptables: DEBUG: Rule op: --flush, chain name: felix-bar
calico.felix.test.test_fiptables: DEBUG: Rule op: --append, chain name: felix-bar
calico.felix.test.test_fiptables: DEBUG: Action ACCEPT
calico.felix.fiptables: INFO: IptablesUpdater<queue_len=0,live=True,msg=None> Successfully processed iptables updates.
calico.felix.fiptables: DEBUG: Batch time: 0.00 1
calico.felix.actor: DEBUG: Message 2f4437abd9cb (cleanup) sent by ActorForTesting (processing None) to IptablesUpdater(v4), queue length 0
calico.felix.actor: DEBUG: Message 2f4437abd9cb (cleanup) recd by IptablesUpdater(v4) from ActorForTesting (processing None), queue length 0
calico.felix.fiptables: INFO: Cleaning up left-over iptables state.
calico.felix.fiptables: INFO: Graceful restart window finished, stubbing out chains: set(['felix-boff', 'felix-baz'])
calico.felix.test.test_fiptables: DEBUG: iptables-restore input:
*filter
:felix-boff -
--flush felix-boff
--append felix-boff --jump DROP -m comment --comment "WARNING Missing chain DROP:"
:felix-baz -
--flush felix-baz
--append felix-baz --jump DROP -m comment --comment "WARNING Missing chain DROP:"
COMMIT
calico.felix.test.test_fiptables: DEBUG: Processing table filter
calico.felix.test.test_fiptables: DEBUG: Forward declaration ['felix-boff', '-'], flushing chain
calico.felix.test.test_fiptables: DEBUG: Rule op: --flush, chain name: felix-boff
calico.felix.test.test_fiptables: DEBUG: Rule op: --append, chain name: felix-boff
calico.felix.test.test_fiptables: DEBUG: Action DROP
calico.felix.test.test_fiptables: DEBUG: Forward declaration ['felix-baz', '-'], flushing chain
calico.felix.test.test_fiptables: DEBUG: Rule op: --flush, chain name: felix-baz
calico.felix.test.test_fiptables: DEBUG: Rule op: --append, chain name: felix-baz
calico.felix.test.test_fiptables: DEBUG: Action DROP
calico.felix.test.test_fiptables: DEBUG: Generating iptables --list for chsins {'felix-foo': ['--append felix-foo --jump felix-bar', '--append felix-foo --jump felix-baz', '--append felix-foo --jump felix-boff'], 'OUTPUT': [], 'ignore-me-too': ['--append ignore-me-too --jump DROP'], 'felix-biff': ['--append felix-biff --src 10.0.0.3/32 --jump DROP'], 'ignore-me': ['--append ignore-me --jump ignore-me-too'], 'felix-bar': ['--append felix-bar --jump ACCEPT'], 'FORWARD': [], 'felix-boff': ['--append felix-boff --jump DROP -m comment --comment "WARNING Missing chain DROP:"'], 'INPUT': [], 'felix-baz': ['--append felix-baz --jump DROP -m comment --comment "WARNING Missing chain DROP:"']}
defaultdict(<type 'set'>, {'felix-foo': set(['felix-bar', 'felix-boff', 'felix-baz']), 'OUTPUT': set([]), 'ignore-me-too': set([]), 'felix-biff': set([]), 'ignore-me': set(['ignore-me-too']), 'felix-bar': set([]), 'FORWARD': set([]), 'felix-boff': set([]), 'INPUT': set([]), 'felix-baz': set([])})
calico.felix.fiptables: DEBUG: Found chain FORWARD, ref count 0
calico.felix.fiptables: DEBUG: Found chain INPUT, ref count 0
calico.felix.fiptables: DEBUG: Found chain OUTPUT, ref count 0
calico.felix.fiptables: DEBUG: Found chain felix-bar, ref count 1
calico.felix.fiptables: DEBUG: Found chain felix-baz, ref count 1
calico.felix.fiptables: DEBUG: Found chain felix-biff, ref count 0
calico.felix.fiptables: DEBUG: Found chain felix-boff, ref count 1
calico.felix.fiptables: DEBUG: Found chain felix-foo, ref count 0
calico.felix.fiptables: DEBUG: Found chain ignore-me, ref count 0
calico.felix.fiptables: DEBUG: Found chain ignore-me-too, ref count 1
calico.felix.fiptables: INFO: Cleanup found these unreferenced chains to delete: set(['felix-biff'])
calico.felix.fiptables: DEBUG: Attempting to delete chains: ['felix-biff']
calico.felix.test.test_fiptables: DEBUG: iptables-restore input:
*filter
:felix-biff -
--delete-chain felix-biff
COMMIT
calico.felix.test.test_fiptables: DEBUG: Processing table filter
calico.felix.test.test_fiptables: DEBUG: Forward declaration ['felix-biff', '-'], flushing chain
calico.felix.test.test_fiptables: DEBUG: Rule op: --delete-chain, chain name: felix-biff
calico.felix.fiptables: DEBUG: Deleted chains ['felix-biff'] successfully, remaining batches: 0
calico.felix.test.test_fiptables: DEBUG: Generating iptables --list for chsins {'felix-foo': ['--append felix-foo --jump felix-bar', '--append felix-foo --jump felix-baz', '--append felix-foo --jump felix-boff'], 'ignore-me-too': ['--append ignore-me-too --jump DROP'], 'ignore-me': ['--append ignore-me --jump ignore-me-too'], 'felix-boff': ['--append felix-boff --jump DROP -m comment --comment "WARNING Missing chain DROP:"'], 'felix-bar': ['--append felix-bar --jump ACCEPT'], 'FORWARD': [], 'OUTPUT': [], 'INPUT': [], 'felix-baz': ['--append felix-baz --jump DROP -m comment --comment "WARNING Missing chain DROP:"']}
defaultdict(<type 'set'>, {'felix-foo': set(['felix-baz', 'felix-boff', 'felix-bar']), 'ignore-me-too': set([]), 'ignore-me': set(['ignore-me-too']), 'felix-boff': set([]), 'felix-bar': set([]), 'FORWARD': set([]), 'OUTPUT': set([]), 'INPUT': set([]), 'felix-baz': set([])})
calico.felix.fiptables: DEBUG: Found chain FORWARD, ref count 0
calico.felix.fiptables: DEBUG: Found chain INPUT, ref count 0
calico.felix.fiptables: DEBUG: Found chain OUTPUT, ref count 0
calico.felix.fiptables: DEBUG: Found chain felix-bar, ref count 1
calico.felix.fiptables: DEBUG: Found chain felix-baz, ref count 1
calico.felix.fiptables: DEBUG: Found chain felix-boff, ref count 1
calico.felix.fiptables: DEBUG: Found chain felix-foo, ref count 0
calico.felix.fiptables: DEBUG: Found chain ignore-me, ref count 0
calico.felix.fiptables: DEBUG: Found chain ignore-me-too, ref count 1
calico.felix.fiptables: INFO: Cleanup finished, deleted 1 chains, failed to delete these chains: set([])
calico.felix.actor: DEBUG: Finishing message batch
calico.felix.fiptables: DEBUG: Chains we'd like to delete: set(['felix-boff', 'felix-baz'])
calico.felix.fiptables: DEBUG: Chains we still need for some reason: set(['felix-boff', 'felix-baz', 'felix-foo', 'felix-bar'])
calico.felix.fiptables: DEBUG: Chains we can delete: set([])
calico.felix.fiptables: DEBUG: Affected chains: deletes=set([]), updates=set([]), stubs=set([])
calico.felix.fiptables: INFO: IptablesUpdater<queue_len=0,live=True,msg=None> no updates in this batch.
calico.felix.fiptables: DEBUG: Batch time: 0.00 1
--------------------- >> end captured logging << ---------------------

======================================================================
ERROR: Failure: OSError (No such file /var/lib/jenkins/workspace/pull-request/calico/acl_manager/test)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/lib/jenkins/workspace/pull-request/.tox/pypy/site-packages/nose/failure.py", line 42, in runTest
    raise self.exc_class(self.exc_val)
OSError: No such file /var/lib/jenkins/workspace/pull-request/calico/acl_manager/test

======================================================================
FAIL: Test a simulated exception leak.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/lib/jenkins/workspace/pull-request/.tox/pypy/site-packages/mock.py", line 1201, in patched
    return func(*args, **keywargs)
  File "/var/lib/jenkins/workspace/pull-request/calico/felix/test/test_actor.py", line 242, in test_exception
    self._m_exit.assert_called_once_with(1)
  File "/var/lib/jenkins/workspace/pull-request/.tox/pypy/site-packages/mock.py", line 303, in assert_called_once_with
    return mock.assert_called_once_with(*args, **kwargs)
  File "/var/lib/jenkins/workspace/pull-request/.tox/pypy/site-packages/mock.py", line 845, in assert_called_once_with
    raise AssertionError(msg)
AssertionError: Expected to be called once. Called 0 times.

======================================================================
FAIL: test_no_exception (calico.felix.test.test_actor.TestExceptionTracking)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/lib/jenkins/workspace/pull-request/.tox/pypy/site-packages/mock.py", line 1201, in patched
    return func(*args, **keywargs)
  File "/var/lib/jenkins/workspace/pull-request/calico/felix/test/test_actor.py", line 265, in test_no_exception
    self.assertEqual(num_refs_at_start, num_refs_at_end)
AssertionError: 28 != 29

======================================================================
FAIL: Really leak an exception-containing result returned via
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/lib/jenkins/workspace/pull-request/.tox/pypy/site-packages/mock.py", line 1201, in patched
    return func(*args, **keywargs)
  File "/var/lib/jenkins/workspace/pull-request/calico/felix/test/test_actor.py", line 280, in test_real_actor_leaked_exc
    self._m_exit.assert_called_once_with(1)
  File "/var/lib/jenkins/workspace/pull-request/.tox/pypy/site-packages/mock.py", line 303, in assert_called_once_with
    return mock.assert_called_once_with(*args, **kwargs)
  File "/var/lib/jenkins/workspace/pull-request/.tox/pypy/site-packages/mock.py", line 845, in assert_called_once_with
    raise AssertionError(msg)
AssertionError: Expected to be called once. Called 0 times.
-------------------- >> begin captured logging << --------------------
calico.felix.actor: INFO: ActorForTesting created.
calico.felix.actor: INFO: Starting ActorForTesting<queue_len=0,live=False,msg=None>
calico.felix.actor: DEBUG: Message 3ba99ac8591a (do_exc) sent by ActorForTesting (processing None) to ActorForTesting, queue length 0
calico.felix.actor: DEBUG: BLOCKING CALL: [d4aec53bae6f] test_actor.py:279:test_real_actor_leaked_exc -> do_a
calico.felix.actor: DEBUG: Message d4aec53bae6f (do_a) sent by ActorForTesting (processing None) to ActorForTesting, queue length 1
calico.felix.actor: DEBUG: Message 3ba99ac8591a (do_exc) recd by ActorForTesting from ActorForTesting (processing None), queue length 0
calico.felix.actor: ERROR: Exception processing 3ba99ac8591a (do_exc)
Traceback (most recent call last):
  File "/var/lib/jenkins/workspace/pull-request/calico/felix/actor.py", line 231, in _step
    result = msg.method()
  File "/usr/lib/pypy/lib_pypy/_functools.py", line 22, in __call__
    return self.func(*(self.args + fargs), **fkeywords)
  File "/var/lib/jenkins/workspace/pull-request/calico/felix/test/test_actor.py", line 332, in do_exc
    raise EXPECTED_EXCEPTION
ExpectedException
calico.felix.actor: DEBUG: Message d4aec53bae6f (do_a) recd by ActorForTesting from ActorForTesting (processing None), queue length 0
calico.felix.actor: DEBUG: Finishing message batch
calico.felix.actor: DEBUG: BLOCKING CALL COMPLETE: [d4aec53bae6f] test_actor.py:279:test_real_actor_leaked_exc -> do_a = 'a'
--------------------- >> end captured logging << ---------------------

----------------------------------------------------------------------
```

**Comment by Lukasa** [comment]
Ok, so here are the test failures and my diagnoses:

- `test_cleanup_with_dependencies`: this fails because it asserts, effectively, that `_on_ref_reaped` will get called when an actor is leaked. Because PyPy doesn't use a refcounted GC, that may or may not get called. We need to consider whether this test is a good idea (or whether it can get tweaked to ensure that it runs correctly on all platforms).
- The `OSError` is weird, there just seems to be some cruft floating around somewhere.
- The other three, again, all appear to be implicitly relying on the refcounted GC.

**Comment by Lukasa** [comment]
Ok, I think I 'fixed' those tests (in that they pass on my Ubuntu machine).

**Comment by fasaxc** [comment]
@Lukasa yep, the leak detection stuff should work with GC but it won't be exact, which the tests rely on.  manually forcing a GC should do the trick.

**Comment by Lukasa** [comment]
And it does: as you'll note, the tests started passing when I committed 1bf004ab2676aef2f192c411b6ab9d5d6b425f12 ;)

**Comment by fasaxc** [comment]
@Lukasa if you've got it working, feels like we should merge even if we don't officially support it yet.  Stop it from rotting at least?

**Comment by fasaxc** [comment]
@Lukasa did you lose the fix for overmocking time?  That bit me the other day.

**Comment by Lukasa** [comment]
Could not agree more about merging this early.

As for losing the mocking fix, yeah, good spot, we lost it. The commit was applied to a file that no longer exists. I'll apply it again to the new location of that change.

**Comment by Lukasa** [comment]
@fasaxc Alright, provided that fix. If @matthewdupre is happy, I think we can merge this.

**Pull request merged**
