### PR TITLE
Implement felix periodic resync.

### PR DESCRIPTION
**Pull request by fasaxc**
* [x] Start another greenlet to periodically trigger a resync.
* [x] Make resync force an update to the dataplane in case anything has been broken by another process
* [x] UT

### CODE REVIEW

**Comment by fasaxc** [comment]
@matthewdupre care to give this a look-over before I write the UT?  We now:

* Add config for the resync interval.
* Start a worker greenlet to trigger the resyncs.
* Pass a force_reprogram flag when doing the resync to ensure the dataplane gets reprogrammed.  (Normally, felix assumes the dataplane won't change under its feet.)

I haven't done anything to interrupt the current outstanding poll, so we'll actually resync after the current poll completes.

**Comment by matthewdupre** [comment]
This looks OK - can you please update the doc as well.

I'm interested in how much testing you've done of this - the reason I'm particularly curious is because most of our tests don't run for long enough to execute this, so we'll have much less live regression testing than usual.

**Comment by fasaxc** [comment]
@matthewdupre I've been running it with a much lower period for my testing, so I see it execute regularly.  I'll touch base with @lwr20 to see if there's a good way to work this into the tests.

**Comment by matthewdupre** [comment]
Just one docs typo, UTs look OK although I haven't reviewed them in detail.

**Comment by fasaxc** [comment]
Fixed.

**Comment by matthewdupre** [comment]
Thanks

**Comment by fasaxc** [comment]
Fixes #325

**Pull request merged**
