### PR TITLE
Let environment override global config file for docker support.

### LINKED ISSUE #326: Add ability to override felix.cfg with environment variables
This makes it much easier to configure felix when it's running under a docker container.

### PR DESCRIPTION
**Pull request by fasaxc**
- felix now allows GLOBAL_ETCDHOST and GLOBAL_ETCDPORT to be
  specified.
- fixes #326.

### CODE REVIEW

**Comment by Lukasa** [comment]
LGTM.

**Comment by fasaxc** [comment]
@spikecurtis under feedback from Neil, I've changed this to use FELIX as the prefix for the variables and combined the ETCD variables into one: FELIX_ETCDADDR=localhost:1234 should do the trick.

**Comment by spikecurtis** [comment]
I tested this out, and it allows me to override the etcd address Felix uses.  Nice!

**Comment by plwhite** [comment]
Again, merging since I think it is good enough for later full review.

**Pull request merged**
