### PR TITLE
Delete old (pre-Felix) Calico agent

### PR DESCRIPTION
**Pull request by neiljerram**

### CODE REVIEW

**Comment by neiljerram** [comment]
When merging this, we should also update our Chef-based FV system so that it installs and runs nova-metadata-api, and (I think) does not run neutron-metadata-agent.

After doing both those things, we can then revert any metadata-related changes from our Neutron fork.

**Comment by neiljerram** [comment]
Hi @Lukasa, assigning this to you for review - and I guess for the Chef change? - now that Jenkins has OK'd it.

**Comment by Lukasa** [comment]
Chef change went in as Metaswitch/calico-chef@3a3cc0d647de7a3d8f4ce005bafe48c84da05e6e.

**Comment by Lukasa** [comment]
Now just waiting on getting the FV rig back.

**Comment by neiljerram** [comment]
Thanks!  Should MetadataPort in felix.cfg be 8775, though?

Otherwise this change LGTM.

------------------

**Pull request merged**
