### PR TITLE
Felix resyncs when the etcd cluster restarts while it's watching

### PR DESCRIPTION
**Pull request by matthewdupre**
This is the Felix part of a fix to issue #340 - it also requires an appropriately patched version of python-etcd (https://github.com/Metaswitch/python-etcd/pull/2)

### CODE REVIEW

**Comment by matthewdupre** [comment]
@fasaxc you might want to take a look too

**Comment by Lukasa** [comment]
This looks plausible, though I'd like to know why the UT failed.

**Comment by matthewdupre** [comment]
The UT is pretty unexciting - it didn't have the right version of python-etcd, so couldn't import the exception.

**Comment by fasaxc** [comment]
I have a pull req open for the same feature, which includes adjusting the python-etcd version and updating tox config: https://github.com/Metaswitch/calico/pull/384 so I'm going to close this one.

**Pull request closed without merging**
