### PR TITLE
Don't resync when config changes

### PR DESCRIPTION
**Pull request by fasaxc**
Conflicted with pull req 376 so I rebased on top of that.  376 needs to be merged to master before this can be reviewed.

Plugin is rewriting config with the same values, triggering a felix resync.  Disable the resync for now.

### CODE REVIEW

**Comment by Lukasa** [comment]
@fasaxc Looks like your commits are wandering around multiple branches: d1cee6a9cba1dd3e4812b55ba859967c677e18b2 was also present in and merged in #369. It should never have been in #369 of course (I thought it was weird when I did a post-hoc review of it), but now that it has been merged there do you mind dropping it from this PR and rebasing?

**Comment by Lukasa** [comment]
In fact, the only new commit in this PR is a1036ec502f403b362ad7e5e9be10855a8c202ce, which doesn't conflict with anything else, so it would be best to just cherry-pick that change in. I'll go ahead and do that.

**Comment by Lukasa** [comment]
Argh, ok, cherry-picking won't work well here either. Blarg. Let's sit on this until I can serialize some of these pull requests.

**Comment by ed-harrison** [comment]
Am I right in thinking this addresses the Felix side of #374?

**Comment by fasaxc** [comment]
@Lukasa Did you see my comment: "Conflicted with pull req 376 so I rebased on top of that. 376 needs to be merged to master before this can be reviewed.".  I figured that, once 376 was merged, then this pull req would only show the deltas on top of that.

Is there a better way to handle such a case?

**Comment by fasaxc** [comment]
@ed-harrison Yes, but I spotted another case where we'll trigger a resync.  I'll raise a separate issue for that.

**Comment by Lukasa** [comment]
@fasaxc I did see that, but the problem was that part of these changes also got merged as part of #369, which means that this PR has a duplicate commit, and merging it will also bring in that duplicate commit. It was *that* that I was trying to avoid, and ideally would like you to fix. =)

**Comment by fasaxc** [comment]
OK, I'll rebase this onto master once #376 is merged.  This one is required for the release.  If we can't get #376 merged then we should manually take the resync changes from this branch and apply to master.

**Comment by robbrockbank** [comment]
This looks good.

**Comment by fasaxc** [comment]
Rebased onto master so it should be only a one tiny commit now.

**Comment by fasaxc** [comment]
@Lukasa please can you pick this up?

**Comment by Lukasa** [comment]
\o/ This looks far nicer, thanks @fasaxc!

**Pull request merged**
