### PR TITLE
Test that characters are valid in tags, rules and endpoints.

### PR DESCRIPTION
**Pull request by plwhite**

### CODE REVIEW

**Comment by plwhite** [comment]
Fixes issue #460

**Comment by plwhite** [comment]
Not ready for merge - tests not available yet.

**Comment by plwhite** [comment]
Cory, got time to review this? Not urgent, but largely a trivial change with enough tests to get coverage (tests could be more comprehensive, but we can come back to that later if necessary- at least covered every branch).

**Comment by plwhite** [comment]
There was a merge clash with a fix by @fasaxc that added tests for overlapping code, now resolved. This has left us with multiple tests of the same method that overlap (neither by itself gets full coverage). I could tidy this up further, but it honestly doesn't seem worth it to me since the test code isn't that horrible and it's just testing dull but worthy and simple firewalling. @Lukasa - back to you to see what you think.

**Comment by matthewdupre** [comment]
Looks fine.

**Pull request merged**
