### PR TITLE
Set up proxy NDP for IPv6

### PR DESCRIPTION
**Pull request by spikecurtis**

### CODE REVIEW

**Comment by spikecurtis** [comment]
ok to build

**Comment by plwhite** [comment]
This isn't the branch we are using for the gevent work - that's gevent-proto. smc-gevent-proto was a temporary working branch that has diverged (although I'm not sure how far it has diverged in practice). I don't want to delete the branch since Shaun was using it, but I'll try merging this manually into gevent-proto so I can at least review it.

**Comment by neiljerram** [comment]
Is this equivalent function to the NDP-related code that has already been merged into Felix on the master branch?

**Comment by plwhite** [comment]
Yes, that's right. Spike sent a mail about it last night.

**Comment by plwhite** [comment]
I have manually merged it into the gevent-proto branch, and am therefore closing this PR.

**Pull request closed without merging**
