### PR TITLE
If we recreate the ACL SUB connection, resubscribe to everything.

### PR DESCRIPTION
**Pull request by plwhite**
Fixes issue #133

### CODE REVIEW

**Comment by neiljerram** [comment]
Note that this PR is for merging into master (not stable1).  Is that what you wanted?

------------------

**Comment by plwhite** [comment]
Note that I have nothing to test this on - calico01 has fallen over yet again, though I will retry. However, the fix is logically correct.

**Comment by plwhite** [comment]
@neiljerram I think I want to merge into stable1 too. Damn. I am not going to sort that out right now, since I am just getting very tired and am in the middle of testing it.

Is that an easy thing to change / do?

**Comment by neiljerram** [comment]
Yes, it's easy - we can sort it out in the morning.

Nothing that you merge now will have any effect on the demo - wherever it's merged to - unless you also do a new release to binaries.projectcalico.org.  And I presume you're not contemplating that now - right?

------------------

**Comment by plwhite** [comment]
OK, so this needs to be rebased onto stable1 to create the right pull request. I am not doing that now; it's too late, I am too tired, and I am just going to screw it up if I try. Let's do that stuff in the morning.

**Comment by neiljerram** [comment]
That sounds sensible to me!

------------------

**Pull request closed without merging**
