### PR TITLE
[DO NOT MERGE] Neutron HA testing branch

### PR DESCRIPTION
**Pull request by matthewdupre**

### CODE REVIEW

**Comment by fasaxc** [comment]
@matthewdupre can this be closed now?

**Comment by matthewdupre** [comment]
No - it contains some commits that add profiling I want to keep.  When I next need to build it, I'll rebase them onto master so it'll look simpler.

**Comment by fasaxc** [comment]
@matthewdupre have you considered making profiling a config option?  I put some profiling hooks in gulfstream and they were very useful.

I'll email you the file.

**Comment by matthewdupre** [comment]
Assigning this to you @plwhite because you're continuing this testing.

Feel free to close this if it's not useful for you.

**Comment by matthewdupre** [comment]
Actually, I'll close this now (but leave the branch there) because it no longer builds and would need rebasing anyway.

**Pull request closed without merging**
