### PR TITLE
[WIP] Neutron changes for HA

### PR DESCRIPTION
**Pull request by Lukasa**
This contains the work done on the Neutron Mechanism Driver for full Neutron HA support.

Work is not complete here: unit tests have been left out until the final architecture is decided. This is primarily being opened to increase visibility into the work, and to allow feedback from people who aren't just me.

### CODE REVIEW

**Comment by Lukasa** [comment]
\o/ :sparkles: :fireworks: This is the first time this branch has been passing unit tests!

**Comment by matthewdupre** [comment]
retest this please

**Comment by matthewdupre** [comment]
Bug in a log statement in endpoint.py: I think endpoint_id must be a tuple or similar.  I've just ripped the log out for my testing version, but worth figuring out what endpoint_id really is and if it gets abused similarly anywhere else.

2015-05-13 16:40:38,310 [ERROR][27803/22] calico.felix.actor 227: Exception processing 4bf9e1320c33 (on_ref_acquired)
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/calico/felix/actor.py", line 225, in _step
    result = msg.method()
  File "/usr/lib/python2.7/dist-packages/calico/felix/refcount.py", line 307, in on_ref_acquired
    self._ready_callback()
  File "/usr/lib/python2.7/dist-packages/calico/felix/endpoint.py", line 392, in _on_profiles_ready
    _log.info("Endpoint %s acquired all required profile references" % self.endpoint_id)
TypeError: not all arguments converted during string formatting
2015-05-13 16:40:38,310 [CRITICAL][27803/22] calico.felix.actor 511: TrackedAsyncResult ('refcount.py:172:_maybe_notify_referrers', 'RulesManager(v6) (processing 96a81d12449b)', u'LocalEndpoint(d8d5194d-6d8c-4265-90e4-e94420f1857b(IPv6))', 'on_ref_acquired') was leaked with exception TypeError('not all arguments converted during string formatting',).  Dying.

**Comment by fasaxc** [comment]
`_log.info("Endpoint %s acquired all required profile references" % self.endpoint_id)` should be `_log.info("Endpoint %s acquired all required profile references", self.endpoint_id)`

**Comment by Lukasa** [comment]
Ok, this is getting tricky to manage with so many branches flying around, so sometime this morning I'm going to land this patch into the `feature/neutron-ha` branch. For that reason, let's make the Felix patch discussed above against that feature branch as well.

Let's start integrating our work, folks! :tada:

**Comment by Lukasa** [comment]
Brilliant, let's move this forward.

My position on this is that the code in this PR represents our stable main-line for HA. Bug fixes to this code are likely to come thick-and-fast in the next few days: that's great, they should be considered high priority. Any logical change to this should go through some design review, though, to make sure that any benefits are worthwhile.

I say this knowing that I plan to provide a logical change to this code in the very near future!

**Pull request merged**
