### PR TITLE
Restart Felix and ACL Manager on RHEL

### PR DESCRIPTION
**Pull request by matthewdupre**
Felix and ACL Manager need to restart on RHEL6 / 7.  This first commit adds the systemd services for RHEL7.

### CODE REVIEW

**Comment by Lukasa** [comment]
I guess this looks plausible. =P

**Comment by matthewdupre** [comment]
ok to test

**Comment by matthewdupre** [comment]
ok to test

**Comment by matthewdupre** [comment]
ok to test

**Comment by matthewdupre** [comment]
ok to test

**Comment by matthewdupre** [comment]
ok to test

**Comment by matthewdupre** [comment]
retest this please

**Comment by matthewdupre** [comment]
@Lukasa This should now be ready for review.  I'll squash the comments down and rebase it once it's OKed.

**Pull request merged**
