### PR TITLE
Issue549redo

### PR DESCRIPTION
**Pull request by plwhite**
Fixes issue #549. Third attempt, after two iterations of breaking stuff not covered in the UTs and extending UTs to cover.

### CODE REVIEW

**Comment by plwhite** [comment]
OK - FV tests pass. Please verify last markups, then merge.

**Comment by matthewdupre** [comment]
Third time's the charm right?

**Comment by matthewdupre** [comment]
No, no it's not.

**Comment by matthewdupre** [comment]
@plwhite - there are still error logs in the FV test output.

**Pull request merged**
