### PR TITLE
Remove workaround for (now fixed) python-iptables bug.

### PR DESCRIPTION
**Pull request by plwhite**
Remove the workaround, but also require version 0.7.0 or better of python-iptables everywhere.

### CODE REVIEW

**Comment by plwhite** [comment]
Oh dear. This works for the `INPUT` and `FORWARD` tables, but not the `felix-INPUT` and `felix-FORWARD` tables (that end up with lots of duplicates). Need to take another look at why that is.

**Comment by plwhite** [comment]
I have now fixed the problems with duplicate rules. This is ready for review.

**Comment by plwhite** [comment]
Fixes bug #35. Well, obviously, but had not put a link in yet.

**Comment by Lukasa** [comment]
LGTM. :cake: :star:

**Pull request merged**
