### PR TITLE
Add some UTs for the iptables Transaction code.

### PR DESCRIPTION
**Pull request by fasaxc**

### CODE REVIEW

**Comment by fasaxc** [comment]
Please don't rebase this, I have it merged into another branch where I'm building on top of it.

**Comment by fasaxc** [comment]
I merged this into the GR stuff because I wanted to build on it there.  If the GR stuff is going to go in, we can close this and just merge it via the other branch.

**Comment by plwhite** [comment]
Happy to merge this, but haven't for now because of the comment about GR (PR # 493).

**Comment by plwhite** [comment]
Actually, since I think we are going to have to hold off a couple of days on the GR stuff, going to merge this now.

**Pull request merged**
