### PR TITLE
Improve a few logs to include IPv4/6 type

### PR DESCRIPTION
**Pull request by plwhite**

### CODE REVIEW

**Comment by plwhite** [comment]
Haven't diagnosed bug #237, so at least fixed up some logs.

**Comment by Lukasa** [comment]
@plwhite I've been seeing that test failure intermittently for a little while now, might be good to fix it if we can.

**Comment by Lukasa** [comment]
Nevermind, that's an ACL manager test.

**Comment by Lukasa** [comment]
At this stage I'm torn, because this is an obvious merge with no real cost, but I'm nervous about the intermittent test failure cascading over to the master branch.

**Comment by Lukasa** [comment]
Ah screw it, when it fails there I can beat @matthewdupre up until he fixes it. =)

**Pull request merged**
