### PR TITLE
Make Felix log its version ID.

### PR DESCRIPTION
**Pull request by plwhite**
Sample output lines : 

    2015-02-09 14:01:15,740 [ERROR] calico.felix.felix 72: Felix starting (calico 0.11)
    2015-02-09 14:01:15,744 [INFO] calico.felix.felix 182: Do total resync - ID : a5089f89-6b0b-4839-96e6-fb5d9c8a56e1 (calico 0.11)

### CODE REVIEW

**Comment by Lukasa** [comment]
This is the most nitty of nits to pick, but it might be worth updating both logs to include a greppable string of some kind ('calico version' jumps to mind). Means if we move them to other logs later we won't lose them.

**Comment by plwhite** [comment]
I have unpicked the nit, and added the same log to ACL Manager (which I should have done in the first place). I selected "version:" as the greppable string, and used it in both places ("calico version calico 0.11" just looked worse than "version: calico 0.11").

**Comment by Lukasa** [comment]
retest this please

**Comment by Lukasa** [comment]
(That was for Jenkins, not you @plwhite)

**Comment by Lukasa** [comment]
retest this please

**Comment by Lukasa** [comment]
retest this please

**Comment by Lukasa** [comment]
retest this please

**Comment by plwhite** [comment]
Fixes isue #109, or at least the non-neutron parts of it.

**Pull request merged**
