### PR TITLE
Add support for list of profiles on endpoints.

### PR DESCRIPTION
**Pull request by fasaxc**
* Profiles are executed in order.  First accept or deny wins.
* The default if there is no match is to drop the packet.
* Single-profile case passed some basic FVs.

Caveats:

* Since we need to return from a chain rather than accept,
  and we need to distinguish explicit return the implicit
  end-of-chain return.  I have used the MARK action to
  distinguish the cases.
* The combination of anti-spoof and profile dispatch in the
  from-endpoint chains is now suboptimal (3nm rules, where
  we could do n+3m instead).
* The tag index is now 4 levels deep which would be a problem
  if we had an endpoint with many IPs, many profiles and
  many tags per profile.  This could be decomposed into
  multiple smaller indices.

### CODE REVIEW

**Comment by fasaxc** [comment]
@Lukasa I think you wanted this to test against tomorrow.  I haven't tested multiple profiles yet but WCGW?

**Comment by fasaxc** [comment]
@Lukasa I've sweetened the deal with some UTs for IpsetManager.  Note: this PR is against your integration branch, not master so I'm expecting we'll give this a good FV before we merge the whole thing together onto master.

**Comment by Lukasa** [comment]
This is with you for review this week @plwhite.

**Comment by fasaxc** [comment]
@plwhite I've been ruminating on this over the weekend and I think it would be cleaner (and better performing) to reify the profiles so that the RulesManager's IDs are tuples containing the sequence of profile IDs.  However, I think that's time that would be better spent elsewhere so I can't justify making that change.

**Comment by plwhite** [comment]
This hit dull merge errors. I therefore have manually merged it (cherry-pick) into feature/neutron-ha, and this can be closed.

**Pull request closed without merging**
