### PR TITLE
Update documentation of configuration for Felix.

### PR DESCRIPTION
**Pull request by plwhite**

### CODE REVIEW

**Comment by plwhite** [comment]
Fixes issue #402.

**Comment by plwhite** [comment]
@neiljerram Not sure if you are the right assignee, but it seemed reasonable as you assigned me the issue!

**Comment by neiljerram** [comment]
Cool, thanks, will look at this tomorrow morning (or perhaps on the train this evening).

**Comment by plwhite** [comment]
Aha. I missed this because it never came back to me! Will reacquire now.

**Comment by neiljerram** [comment]
Sorry about that!

**Comment by plwhite** [comment]
No problem, back to you. Just tweaked a couple of descriptions where the old version was better, as you suggested.

**Pull request merged**
